<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/170624/1-1F624222006.png ",93,239);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/170624/1-1F624222006.png";
$z[1][4]['text']="";
$z[1][4]['width']="1200";
$z[1][4]['height']="600";
$z[2]=Array("img"," /uploads/allimg/170624/1-1F624222014.png ",241,387);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/170624/1-1F624222014.png";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="600";
$z[3]=Array("img"," /uploads/allimg/170624/1-1F624222017.png ",389,535);
$z[3][4]=array();
$z[3][4]['ddimg']="/uploads/allimg/170624/1-1F624222017.png";
$z[3][4]['text']="";
$z[3][4]['width']="1200";
$z[3][4]['height']="600";

?>