<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]=array();
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/170208/1-1F20R22122.jpg ",93,237);
$z[1][4]=array();
$z[1][4]['ddimg']="/uploads/allimg/170208/1-1F20R22122.jpg";
$z[1][4]['text']="";
$z[1][4]['width']="1400";
$z[1][4]['height']="778";
$z[2]=Array("img"," /uploads/allimg/170208/1-1F20R22123.jpg ",239,384);
$z[2][4]=array();
$z[2][4]['ddimg']="/uploads/allimg/170208/1-1F20R22123.jpg";
$z[2][4]['text']="";
$z[2][4]['width']="1200";
$z[2][4]['height']="1729";

?>