<?php
$z[0]=Array("autoindex","@me=\$GLOBALS['autoindex']-1;",20,96);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",154,169);
$z[1][4]=array();
$z[2]=Array("picname","",339,355);
$z[2][4]=array();
$z[3]=Array("title","",536,550);
$z[3][4]=array();
$z[4]=Array("shorttitle","",610,629);
$z[4][4]=array();
$z[5]=Array("description","",697,763);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\").\"\",250)";

?>