<?php
$z[0]=Array("id","",79,90);
$z[0][4]=array();
$z[1]=Array("picname","",134,150);
$z[1][4]=array();
$z[2]=Array("pubdate","",244,289);
$z[2][4]=array();
$z[2][4]['function']="MyDate('m-d',@me)";
$z[3]=Array("pubdate","",321,364);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Y',@me)";
$z[4]=Array("title","",454,468);
$z[4][4]=array();
$z[5]=Array("description","",507,557);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,200)";

?>