<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	

<field:mp4 itemname="MP4视频" autofield="1" notsend="0" type="media" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:mp4>

<field:taempic itemname="团队照片" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:taempic>
