<li id="teamitem_0"  class="wow">
            <div class="header wow" data-wow-delay=".2s"><a href="[field:arcurl/]" target="_blank"><img src="[field:picname/]" width="180" height="180" /></a></div>
            <div class="summary wow">
              <p class="title"><a href="[field:arcurl/]">[field:title/]</a></p>
                            <p class="subtitle">[field:shorttitle/]</p>
                            <p class="description wow">[field:description function='cn_substr(Html2text("@me")."",250)'/]</p>
            </div>
            <a href="[field:arcurl/]" target="_blank" class="details">more<i class="fa fa-angle-right"></i></a>
          </li>