<?php
$z[0]=Array("arcurl","",101,116);
$z[0][4]=array();
$z[1]=Array("picname","",144,160);
$z[1][4]=array();
$z[2]=Array("arcurl","",280,295);
$z[2][4]=array();
$z[3]=Array("title","",297,311);
$z[3][4]=array();
$z[4]=Array("shorttitle","",369,388);
$z[4][4]=array();
$z[5]=Array("description","",449,515);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\").\"\",250)";
$z[6]=Array("arcurl","",562,577);
$z[6][4]=array();

?>