<li id="projectitem_[field:autoindex runphp='yes']@me=$GLOBALS['autoindex']-1;[/field:autoindex]" class="projectitem wow">
                 <a href="[field:arcurl/]" class="projectitem_content" target="_blank">
                    <div class="projectitem_wrapper">
                        <div class="project_img"><img src="[field:picname/]" width="650" height="385"/></div>
                        <div class="project_info">
                           <div>
                              <p class="title">[field:title/]</p>
                              <p class="subtitle">[field:shorttitle/]</p>
                           </div>
                        </div>
                    </div>
                  </a>
               </li>