<ul class="slider one">
                    <li>
            <div class="header wow" data-wow-delay=".2s">
              <p class="title">[field:typename/]</p>
          <p class="subtitle">[field:engtype/]</p>
              </div>
            <div class="des-wrap">
              <p class="description wow" data-wow-delay=".3s">[field:description function='cn_substr(Html2text("@me")."...",800)'/]...</p>
            </div>
            <a href="[field:typelink/]" class="more wow" data-wow-delay=".5s">MORE<i class="fa fa-angle-right"></i></a>            <div class="fimg wow" style="background-image:url(/xunmoban/pic/habout.jpg)"></div>
            </li>
                  </ul>