<?php
$z[0]=Array("autoindex","@me=\$GLOBALS['autoindex']-1;",20,96);
$z[0][4]=array();
$z[0][4]['runphp']="yes";
$z[1]=Array("id","",167,178);
$z[1][4]=array();
$z[2]=Array("picname","",348,364);
$z[2][4]=array();
$z[3]=Array("title","",545,559);
$z[3][4]=array();
$z[4]=Array("shorttitle","",619,638);
$z[4][4]=array();
$z[5]=Array("description","",706,772);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(Html2text(\"@me\").\"\",250)";

?>