<div class="projectitem wow fadeIn"><a href="view.php?aid=[field:id/]">
          <div class="project_img"><img src="[field:picname/]" width="500" height="320"/></div>
          <div class="project_info">
            <div>
              <p class="title">[field:title/]</p>
              <p class="subtitle">[field:shorttitle/]</p>
              <p class="description">[field:description function='cn_substr(Html2text("@me")."...",250)'/]</p>
              
            </div>
          </div>
          </a></div>