<?php
$z[0]=Array("arcurl","",31,46);
$z[0][4]=array();
$z[1]=Array("picname","",91,107);
$z[1][4]=array();
$z[2]=Array("arcurl","",351,366);
$z[2][4]=array();
$z[3]=Array("title","",368,382);
$z[3][4]=array();
$z[4]=Array("shorttitle","",424,443);
$z[4][4]=array();
$z[5]=Array("description","",484,534);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,200)";
$z[6]=Array("arcurl","",577,592);
$z[6][4]=array();

?>