<div class="teamitem"><a href="[field:arcurl/]">
          <div class="teamimg"><img src="[field:picname/]" width="320" height="320" /></div>
          <div class="wrap">
            <div><span class="h"></span><span class="v"></span></div>
          </div>
          </a>
          <div class="teaminfo">
            <p class="title"><a href="[field:arcurl/]">[field:title/]</a></p>
            <p class="subtitle">[field:shorttitle/]</p>
            <p class="description">[field:description function="cn_substr(@me,200)"/]</p>
          </div>
          <a href="[field:arcurl/]" target="_blank" class="details">more<i class="fa fa-angle-right"></i></a>
        </div>